spring:
  profiles:
    active: dev
  datasource:
      url: jdbc:sqlserver://localhost:1433;databaseName=springBoot;encrypt=true;trustServerCertificate=true
      username: sa
      password: P@ssw0rd123
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.SQLServerDialect
server:
    port: 8088

---
spring:
  config:
    activate:
      on-profile: dev

---